# Generated by Django 3.2.7 on 2021-09-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('video_type', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('video_number', models.IntegerField()),
                ('transcription', models.JSONField(default=dict)),
            ],
        ),
    ]
