# Generated by Django 3.2.7 on 2021-09-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210926_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
    ]
